### ISSUE TITLE
Interactive marker TF calibration

### ISSUE THREAD

**Issue by awesomebytes** [PickNikRobotics/tf_keyboard_cal#2]
Hey Dave,

Seeing this package, I got an isolated python ROS node to do something similar:
https://gist.github.com/awesomebytes/2aa18ba3b821b2f580a2

It publishes an Interactive Marker that you can move around and it will be publishing the TF transform (you can also stop it publishing). Also a PoseStamped, useful for debugging. And in the terminal it spits out the transformation in the format of static_transform_publisher and URDF.

You can just watch it work here: https://www.youtube.com/watch?v=C9BbFv-C9Zo

If you want to merge it into your package feel free, or I can do a PR. Altho it's useful as you can run it standalone, it only depends on interactive markers, tf and geometry_msgs. Being python it doesn't even need to be in a catkin package.

**Comment by davetcoleman** [comment]
That's great, I've wanted to make one of those for the longest time but always convinced myself it wasn't a good time investment since I already created the keyboard cal. I think this would be a great contribution to add in! Could you create a PR including changing the README.md a bit to explain how it works? An example roslaunch file is always really helpful, too.

**Comment by awesomebytes** [comment]
Sure, I'll do it soon!

**Comment by awesomebytes** [comment]
There it is https://github.com/davetcoleman/tf_keyboard_cal/pull/3 :)

**Comment by davetcoleman** [comment]
I also added a screenshot just now and linked to this project from http://wiki.ros.org/tf2
